import Navbar from "@/components/navbar"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { cn } from "@/lib/utils"
import Header from "@/components/header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "GET theme",
	description: "Generated by create next app",
}

export const dynamic = 'force-dynamic'
export const revalidate = 0

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={cn(
					inter.className,
					"flex flex-col h-screen overflow-hidden"
				)}
			>
				{/* <Navbar /> */}
				<Header />
				<main className=" flex-1 overflow-auto">
					<div className="max-w-[960px] w-full mx-auto px-4 my-8">
						{children}
					</div>
				</main>
			</body>
		</html>
	)
}
